// Architectural styles for k.arch.building: plain data, no code. A style says how big floors,
// bays and openings are, which modules dress the facade (window heads, quoins, bands, timber
// framing, dormers, chimneys, portico) and which finish each material zone gets.
//
// Zones: wall, trim, roof, frame, glass, door, metal, timber, chimney, shutter. A finish is
// { kind, color, ... } or the name of another zone (an alias: chimney: 'wall').
// Finish kinds: brick, ashlar, rubble, plaster, concrete, slate, clay-tiles, thatch, zinc, timber, paint,
// glass, iron. `tile` = meters per texture repeat.
//
// A new style is a new entry (or `{ extends: 'georgian', ...overrides }` passed as `style`).

export const STYLES = {
  georgian: {
    label: 'Georgian manor: symmetrical brick facade, stone trim, sash windows, hipped slate roof',
    wallThickness: 0.5,
    groundFloorHeight: 4.4,
    floorHeight: 3.5,
    plinth: { height: 0.75, projection: 0.08 },
    bay: { width: 2.8, min: 2.2, margin: 1.3, symmetric: true },
    floorZones: { ground: 'wall', upper: 'wall', top: 'wall' },
    windowDefaults: {
      shape: 'rect',
      frame: { border: 0.12, depth: 0.07, zone: 'trim' },
      mullions: [3, 3],
      head: 'lintel',
      sillBlock: true,
      shutters: false,
      balcony: null,
    },
    windows: {
      ground: { w: 1.15, h: 2.1, sill: 0.8, head: 'keystone' },
      noble: { w: 1.15, h: 2.3, sill: 0.45, mullions: [3, 4], head: 'pediment' },
      upper: { w: 1.1, h: 1.9, sill: 0.7 },
      top: { w: 1.05, h: 1.4, sill: 0.7, mullions: [3, 2] },
    },
    door: { w: 1.4, h: 2.6, fanlight: true, surround: 'pilasters', pediment: true, leaf: 'double', zone: 'trim' },
    bands: {
      stringCourse: [[0.22, 0.06]],
      cornice: [[0.18, 0.05], [0.12, 0.12], [0.22, 0.28]],
    },
    quoins: { height: 0.36, long: 0.62, short: 0.38, depth: 0.035 },
    roof: { type: 'hip', pitch: 30, overhang: 0.15, thickness: 0.3 },
    dormers: { pattern: 'alternate', w: 0.95, h: 1.2, setback: 0.8, zone: 'roof' },
    chimneys: { count: 2, placement: 'ends', w: 1.2, d: 0.75, above: 1.3 },
    portico: null,
    timber: null,
    jetty: null,
    finishes: {
      wall: { kind: 'brick', color: '#9b4a35', mortar: '#d6ccbc', tile: 1.2 },
      trim: { kind: 'ashlar', color: '#ddd5c4', mortar: '#b5aa96', tile: 1.8 },
      roof: { kind: 'slate', color: '#4a5058', tile: 1.5 },
      frame: { kind: 'paint', color: '#f1eee6' },
      glass: { kind: 'glass', color: '#1c2630' },
      door: { kind: 'paint', color: '#1f2b26' },
      metal: { kind: 'iron', color: '#2d3033' },
      timber: 'frame',
      chimney: 'wall',
      shutter: 'door',
    },
  },

  'medieval-timber': {
    label: 'Medieval timber-framed house: stone ground floor, jettied plastered upper floors with dark oak framing, steep tiled gable roof',
    wallThickness: 0.35,
    groundFloorHeight: 2.9,
    floorHeight: 2.7,
    plinth: { height: 0.35, projection: 0.06 },
    bay: { width: 2.3, min: 1.8, margin: 0.8, symmetric: false },
    floorZones: { ground: 'trim', upper: 'wall', top: 'wall' },
    windowDefaults: {
      shape: 'rect',
      frame: { border: 0.1, depth: 0.06, zone: 'timber' },
      mullions: [3, 3],
      head: 'none',
      sillBlock: false,
      shutters: false,
      balcony: null,
    },
    windows: {
      ground: { w: 0.85, h: 1.1, sill: 0.95, mullions: [2, 2], head: 'lintel' },
      upper: { w: 0.95, h: 1.15, sill: 0.85 },
    },
    door: { w: 1.05, h: 2.0, shape: 'arch', fanlight: false, surround: 'frame', leaf: 'single', zone: 'timber' },
    bands: { stringCourse: [], cornice: [] },
    quoins: null,
    roof: { type: 'gable', pitch: 52, overhang: 0.45, thickness: 0.28 },
    dormers: null,
    chimneys: { count: 1, placement: 'ends', w: 0.9, d: 0.8, above: 1.0 },
    portico: null,
    timber: { floors: ['upper', 'top'], beam: 0.2, depth: 0.05, braces: 'chevron' },
    jetty: { amount: 0.4, sides: ['front', 'back'] },
    finishes: {
      wall: { kind: 'plaster', color: '#e4d9bf', tile: 2 },
      trim: { kind: 'rubble', color: '#9a948a', mortar: '#6d675d', tile: 1.6 },
      roof: { kind: 'clay-tiles', color: '#8e4b33', tile: 1.4 },
      timber: { kind: 'timber', color: '#3b2a1e', tile: 1.5 },
      frame: 'timber',
      glass: { kind: 'glass', color: '#26303a' },
      door: 'timber',
      metal: { kind: 'iron', color: '#2d3033' },
      chimney: 'trim',
      shutter: 'door',
    },
  },

  'paris-haussmann': {
    label: 'Parisian Haussmann apartment block: cream ashlar, wrought-iron balconies on the 2nd and 5th floors, cornices over the windows, zinc mansard with dormers',
    wallThickness: 0.55,
    groundFloorHeight: 4.6,
    floorHeight: 3.2,
    plinth: { height: 0.3, projection: 0.04 },
    bay: { width: 3.0, min: 2.4, margin: 1.0, symmetric: true },
    floorZones: { ground: 'trim', upper: 'wall', top: 'wall' },
    windowDefaults: {
      shape: 'rect',
      frame: { border: 0.14, depth: 0.06, zone: 'trim' },
      mullions: [2, 4],
      head: 'lintel',
      sillBlock: true,
      shutters: false,
      balcony: null,
    },
    windows: {
      ground: { w: 2.0, h: 3.2, sill: 0.15, shape: 'arch', mullions: [3, 4], head: 'keystone', sillBlock: false },
      noble: { w: 1.25, h: 2.45, sill: 0.08, head: 'cornice', balcony: { depth: 0.75, zone: 'metal' } },
      upper: { w: 1.2, h: 2.25, sill: 0.4, head: 'lintel', balcony: { depth: 0.12, zone: 'metal' } },
      top: { w: 1.2, h: 2.2, sill: 0.08, head: 'lintel', balcony: { depth: 0.6, zone: 'metal' } },
    },
    door: { w: 2.4, h: 3.0, shape: 'arch', fanlight: true, surround: 'frame', leaf: 'double', zone: 'trim' },
    bands: { stringCourse: [[0.22, 0.05]], cornice: [[0.2, 0.06], [0.14, 0.18], [0.24, 0.42]] },
    quoins: null,
    roof: { type: 'mansard', lowerPitch: 72, lowerHeight: 2.8, upperPitch: 18, overhang: 0.08, thickness: 0.2 },
    dormers: { pattern: 'all', w: 1.0, h: 1.5, setback: 0.35, depth: 1.4, zone: 'roof' },
    chimneys: { count: 4, placement: 'ridge', w: 1.5, d: 0.6, above: 0.8 },
    portico: null,
    timber: null,
    jetty: null,
    finishes: {
      wall: { kind: 'ashlar', color: '#e2d6bd', mortar: '#c8b99c', tile: 1.6 },
      trim: { kind: 'ashlar', color: '#d9ccb1', mortar: '#bfae8f', tile: 1.6 },
      roof: { kind: 'zinc', color: '#8c949a', tile: 1.2 },
      frame: { kind: 'paint', color: '#ece9e1' },
      glass: { kind: 'glass', color: '#1e2832' },
      door: { kind: 'paint', color: '#2a3f35' },
      metal: { kind: 'iron', color: '#1f2224' },
      chimney: 'trim',
      shutter: 'door',
      timber: 'frame',
    },
  },

  modern: {
    label: 'Modern house: smooth white render, large dark-framed windows, concrete base, flat roof with a parapet',
    wallThickness: 0.35,
    groundFloorHeight: 3.3,
    floorHeight: 3.1,
    plinth: { height: 0.15, projection: 0.02 },
    bay: { width: 3.2, min: 2.4, margin: 0.9, symmetric: false },
    floorZones: { ground: 'wall', upper: 'wall', top: 'wall' },
    windowDefaults: {
      shape: 'rect',
      frame: { border: 0.05, depth: 0.04, zone: 'frame' },
      mullions: [2, 1],
      head: 'none',
      sillBlock: false,
      shutters: false,
      balcony: null,
    },
    windows: {
      ground: { w: 2.4, h: 2.4, sill: 0.25 },
      upper: { w: 2.0, h: 2.0, sill: 0.6 },
    },
    door: { w: 1.2, h: 2.4, fanlight: false, surround: 'frame', leaf: 'single', zone: 'frame' },
    bands: { stringCourse: [], cornice: [[0.7, 0.03]] },
    quoins: null,
    roof: { type: 'flat', overhang: 0.0, thickness: 0.25 },
    dormers: null,
    chimneys: null,
    portico: null,
    timber: null,
    jetty: null,
    finishes: {
      wall: { kind: 'plaster', color: '#eceae5', tile: 2 },
      trim: { kind: 'concrete', color: '#a4a29d', tile: 2.4 },
      roof: { kind: 'concrete', color: '#7d7b77', tile: 2.4 },
      frame: { kind: 'paint', color: '#2b2e33', roughness: 0.4 },
      glass: { kind: 'glass', color: '#22303a' },
      door: { kind: 'timber', color: '#8a6440', tile: 1.2 },
      metal: { kind: 'iron', color: '#2b2e33' },
      chimney: 'trim',
      shutter: 'door',
      timber: 'door',
    },
  },
};
