-- VerifyGolden: checks the golden models imported into Roblox Studio against GoldenManifest
-- (generated by `node studio engine-pack roblox`).
--
-- Two ways to run it:
--   1. Open engines/roblox/GoldenVerify.rbxlx, import the GLBs from engines/roblox/golden/ into
--      Workspace > GoldenImports (File > Import 3D, Scale Unit: Stud), then press Play or Run.
--      This script is ServerScriptService > VerifyGolden in that place.
--   2. Paste this whole file into the Command Bar (View > Command Bar) in the same place.
--
-- For every manifest item it finds the imported model by name and checks:
--   size in studs (Model:GetExtentsSize), MeshPart count (one per exported mesh), that every
--   MeshPart carries a texture (colors are baked into textures for Roblox), and DoubleSided off.
-- Results go to the Output window and to attributes on Workspace.GoldenImports.

local ServerScriptService = game:GetService("ServerScriptService")
local manifestModule = ServerScriptService:FindFirstChild("GoldenManifest")
if not manifestModule then
	error("GoldenManifest ModuleScript not found in ServerScriptService. Run `node studio engine-pack roblox` and open engines/roblox/GoldenVerify.rbxlx.")
end
local manifest = require(manifestModule)

local SIZE_REL = 0.02 -- 2 % of the expected size
local SIZE_ABS = 0.05 -- studs

local imports = workspace:FindFirstChild("GoldenImports") or workspace

local function findImported(name)
	for _, d in ipairs(imports:GetDescendants()) do
		if d.Name == name and (d:IsA("Model") or d:IsA("BasePart")) then
			return d
		end
	end
	return nil
end

local function meshPartsOf(root)
	local list = {}
	if root:IsA("MeshPart") then
		table.insert(list, root)
	end
	for _, d in ipairs(root:GetDescendants()) do
		if d:IsA("MeshPart") then
			table.insert(list, d)
		end
	end
	return list
end

local function extentsOf(root)
	if root:IsA("Model") then
		return root:GetExtentsSize()
	end
	return root.Size
end

local function read(instance, property)
	local ok, value = pcall(function()
		return instance[property]
	end)
	if ok then
		return value
	end
	return nil
end

local function isTextured(part)
	local textureId = read(part, "TextureID")
	if typeof(textureId) == "string" and textureId ~= "" then
		return true
	end
	return part:FindFirstChildOfClass("SurfaceAppearance") ~= nil
end

local function fmt(v)
	return string.format("%.2f x %.2f x %.2f", v.X, v.Y, v.Z)
end

local passed, failed, missing = 0, 0, 0
local lines = {}

for _, item in ipairs(manifest.items) do
	-- The importer names the model after the file (or the root node, depending on the version).
	local model = findImported(item.name) or findImported(item.rootNode)
	if not model then
		missing += 1
		table.insert(lines, string.format("MISSING  %s  (import golden/%s into GoldenImports)", item.id, item.file))
	else
		local problems = {}
		local size = extentsOf(model)
		local expected = Vector3.new(item.sizeStuds[1], item.sizeStuds[2], item.sizeStuds[3])
		for _, axis in ipairs({ "X", "Y", "Z" }) do
			if math.abs(size[axis] - expected[axis]) > math.max(SIZE_ABS, expected[axis] * SIZE_REL) then
				table.insert(problems, string.format("size %s studs, expected %s", fmt(size), fmt(expected)))
				break
			end
		end
		local parts = meshPartsOf(model)
		if #parts ~= item.meshParts then
			table.insert(problems, string.format("%d MeshParts, expected %d", #parts, item.meshParts))
		end
		local untextured, doubleSided = 0, 0
		for _, part in ipairs(parts) do
			if item.textured and not isTextured(part) then
				untextured += 1
			end
			if read(part, "DoubleSided") == true then
				doubleSided += 1
			end
		end
		if untextured > 0 then
			table.insert(problems, string.format("%d MeshPart(s) without texture (colors lost)", untextured))
		end
		if doubleSided > 0 then
			table.insert(problems, string.format("%d MeshPart(s) are DoubleSided", doubleSided))
		end
		if #problems == 0 then
			passed += 1
			table.insert(lines, string.format("PASS     %s  %s studs, %d MeshPart(s)", item.id, fmt(size), #parts))
		else
			failed += 1
			table.insert(lines, string.format("FAIL     %s  %s", item.id, table.concat(problems, "; ")))
		end
	end
end

for _, line in ipairs(lines) do
	print(line)
end
local tested = passed + failed
local summary = string.format(
	"Golden verify (Roblox): %d/%d imported items passed, %d not imported. Triangle counts are shown by the importer (expected values: GoldenManifest).",
	passed,
	tested,
	missing
)
print(summary)
if imports ~= workspace then
	imports:SetAttribute("GoldenPassed", passed)
	imports:SetAttribute("GoldenFailed", failed)
	imports:SetAttribute("GoldenMissing", missing)
end
